# Generated by Django 3.2.7 on 2021-09-03 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credfinanceapp', '0002_userprofile_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ManyToManyField(to='credfinanceapp.Wallet')),
            ],
        ),
    ]
