# Generated by Django 3.2.7 on 2021-09-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credfinanceapp', '0004_auto_20210903_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bvn_verified',
            field=models.BooleanField(default=False),
        ),
    ]
