# Generated by Django 3.2.7 on 2021-09-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credfinanceapp', '0005_userprofile_bvn_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
