# Generated by Django 3.2.7 on 2021-09-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credfinanceapp', '0006_alter_walletbalance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bvn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
