# Generated by Django 3.2.7 on 2021-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credfinanceapp', '0007_alter_userprofile_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='wallet',
            field=models.ManyToManyField(blank=True, to='credfinanceapp.Wallet'),
        ),
    ]
